language: java
jdk:
  - openjdk8
after_success:
  - if [ $TRAVIS_JDK_VERSION = 'openjdk8' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
  - if [ $TRAVIS_JDK_VERSION = 'openjdk8' ]; then mvn clean cobertura:cobertura coveralls:report; fi
env:
  global:
    secure: qd20UmZR2wd9gZqIJieEsxrMD212I8+dJQ9k0B7YMTf1PtyM1LHxZog2sv1/h0GF7FFp0xhanDNXBxfAbPqFI3TebpxVL/8tQOomsKJl+VL/5ZWSNugTNHTMdEwTWuKFm08u2tZ8Zwl7vK7mhKV+B/NJxl7ySWvtn9+rfsWaPDPcj7TC4QdbUet51Hxf85Lca03UHeqGHYUgv1iYxvRznnOUmzPHS+pYVrBzh3MITLnq0LrRfN+Bh1cHQ8kd65Ze1pVICrDkS1w8fUqkyceWEwg9pjEmemJoSzFnYUqcFAqj4eCaqL5toDyo4x7kPFJ9OhEFCHiqioj8nEclFKCmwqgH/d/V36q3Wa0ibgz+HNMflH6Cx4g3WPx7gqalNrpAqys/FfsdXpmmtK3TiYArJvhuX77fo71tZn34XkhTzimelDYZi9v4FJLKmTh+b6UqjOKbwI8qcFqdoo6W0ACwQklEBpTMwzpOQK/cnFR885j85EJuYxOOxwckqFKE9i0rUKRHrMPrhN86p7XF54VZmy3W0NcN4TRIxWb1323gXpB/E0pvjv3k9F0L5pgQiB0cSyw7GVLfBLbjpb9RteevStwlYHmbswK0184KO02oYGDKVjh/NEHslUHLMk1Awr+gwflCnNAXM2OlqaVFFngsSfQ+OiyQq+7xjC9sLay2AuM=

script:
  mvn verify -B
