name: Java SDK CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [8, 11, 16, 17]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Build and Test
        run: mvn verify -B
