name: Dependency Review

on:
  push:
    branches: ['master']
    
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  dependency-review:
    uses: hyperwallet/public-security-workflows/.github/workflows/dependency-review.yml@datadog
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_PAYPAL_QA_TOKEN }}        